name: Build

on:
  release:
    types: [created]

permissions:
  contents: write     # needed to upload assets

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools musl-dev
        
    - name: Add MUSL target
      run: rustup target add x86_64-unknown-linux-musl
        
    - name: Build with MUSL
      run: cargo build --release --target x86_64-unknown-linux-musl
      
    - name: Package static binary
      run: |
        mkdir -p package
        cp target/x86_64-unknown-linux-musl/release/qzn3t_pad package/
        strip package/qzn3t_pad  # Optional: reduce binary size
        tar czvf qzn3t_pad-linux-static-x86_64.tar.gz -C package .
        
    - name: Upload file as release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./qzn3t_pad-linux-static-x86_64.tar.gz
        asset_name: qzn3t_pad-linux-static-x86_64.tar.gz
        asset_content_type: application/gzip
        
