name: MacOS Build

on:
  release:
    types: [created]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build_macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: macos-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Setup Rust toolchain
      run: |
        rustup target add x86_64-apple-darwin

    - name: Build for macos-x86_64
      run: cargo build --release --target x86_64-apple-darwin
      
    - name: Package binary
      run: |
        mkdir -p package
        binary_name="qzn3t_pad"
        cp target/x86_64-apple-darwin/release/$binary_name package/
        cd package
        zip -r ../qzn3t_pad-macos-x86_64.zip .
        
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: qzn3t_pad-macos-x86_64.zip
        asset_name: qzn3t_pad-macos-x86_64.zip
        asset_content_type: application/zip
