name: Linux x86_64 Build (musl)

on:
  release:
    types: [created]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build_x86_64:
    runs-on: debian-12

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: linux-x86_64-cargo-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools

    - name: Setup Rust toolchain
      run: |
        rustup target add x86_64-unknown-linux-musl
        rustup component add rust-std-x86_64-unknown-linux-musl

    - name: Configure build environment
      run: |
        echo "RUSTFLAGS=-C target-feature=+crt-static" >> $GITHUB_ENV
        echo "CC=musl-gcc" >> $GITHUB_ENV

    - name: Build for linux-x86_64
      run: cargo build --release --target x86_64-unknown-linux-musl
      
    - name: Package binary
      run: |
        mkdir -p package
        binary_name="qzn3t_pad"
        cp target/x86_64-unknown-linux-musl/release/$binary_name package/
        tar czvf qzn3t_pad-linux-x86_64.tar.gz -C package .
        
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: qzn3t_pad-linux-x86_64.tar.gz
        asset_name: qzn3t_pad-linux-x86_64.tar.gz
        asset_content_type: application/gzip
